name: vquiz_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  flutter_svg: ^2.0.7
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  dartz: ^0.10.1
  meta: ^1.9.1
  flutter_overlay_loader: ^2.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/.env
    - assets/images/




